basePath: /
definitions:
  main.ProductDTO:
    properties:
      code:
        type: string
      price:
        type: integer
    type: object
host: localhost:9000
info:
  contact:
    email: marckenneth.lomio@gmail.com
    name: Marc Kenneth Lomio
  description: Go Rest API with SQL SERVER DB
  title: Go Rest API
  version: "1.0"
paths:
  /migration:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Migrate tables to the SQL Server
      tags:
      - migration
  /product:
    post:
      parameters:
      - description: Create product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.ProductDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ProductDTO'
      summary: Create Product
      tags:
      - products
  /product/{id}:
    get:
      parameters:
      - description: Get id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ProductDTO'
      summary: Get specific Product
      tags:
      - products
  /products:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get all products
      tags:
      - products
swagger: "2.0"
